apiVersion: v1
kind: Service
metadata:
  name: {{ include "socket-firewall.fullname" . }}
  labels:
    {{- include "socket-firewall.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ if .Values.service.httpsTargetPort }}{{ .Values.service.httpsTargetPort }}{{ else }}https{{ end }}
      protocol: TCP
      name: https
  selector:
    {{- include "socket-firewall.selectorLabels" . | nindent 4 }}
