{{- if .Values.upstreamTokens.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "socket-firewall.upstreamTokensSecretName" . }}
  labels:
    {{- include "socket-firewall.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.upstreamTokens.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
